packages:
  - apps/*
  - packages/*

catalog:
  typescript: ~5.6.2
  prettier: ^3.2.5

catalogs:
  vite:
    vite: ^6.0.5
    '@vitejs/plugin-react': ^4.3.4
    '@originjs/vite-plugin-federation': ^1.3.8
  react:
    react: ^18.3.1
    react-dom: ^18.3.1
    '@types/react': ^18.3.3
    '@types/react-dom': ^18.3.0
  react-query:
    '@tanstack/react-query': ^5.62.7
    '@tanstack/react-query-devtools': ^5.62.7
    '@tanstack/eslint-plugin-query': ^5.62.9
  react-router:
    '@tanstack/react-router': ^1.95.3
    '@tanstack/zod-adapter': ^1.95.3
    '@tanstack/router-devtools': ^1.95.3
    '@tanstack/router-plugin': ^1.95.3
