/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticationLoginCallbackImport } from './routes/authentication/login-callback'
import { Route as AuthenticationLoginImport } from './routes/authentication/login'
import { Route as AuthenticatedSitesImport } from './routes/_authenticated/sites'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationLoginCallbackRoute =
  AuthenticationLoginCallbackImport.update({
    id: '/authentication/login-callback',
    path: '/authentication/login-callback',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticationLoginRoute = AuthenticationLoginImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSitesRoute = AuthenticatedSitesImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginImport
      parentRoute: typeof rootRoute
    }
    '/authentication/login-callback': {
      id: '/authentication/login-callback'
      path: '/authentication/login-callback'
      fullPath: '/authentication/login-callback'
      preLoaderRoute: typeof AuthenticationLoginCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/sites': typeof AuthenticatedSitesRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/login-callback': typeof AuthenticationLoginCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/sites': typeof AuthenticatedSitesRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/login-callback': typeof AuthenticationLoginCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/login-callback': typeof AuthenticationLoginCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sites'
    | '/authentication/login'
    | '/authentication/login-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/sites'
    | '/authentication/login'
    | '/authentication/login-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/sites'
    | '/authentication/login'
    | '/authentication/login-callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationLoginCallbackRoute: typeof AuthenticationLoginCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationLoginCallbackRoute: AuthenticationLoginCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/authentication/login",
        "/authentication/login-callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/sites"
      ]
    },
    "/_authenticated/sites": {
      "filePath": "_authenticated/sites.tsx",
      "parent": "/_authenticated"
    },
    "/authentication/login": {
      "filePath": "authentication/login.tsx"
    },
    "/authentication/login-callback": {
      "filePath": "authentication/login-callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
